Remove extraneous commas in csv fields
The extra commas would sometimes cause the application to abort:

Alice is more intelligent than Brad

[]
Answer answerA
Row fact {'id': '39', 'word': 'more intelligent', 'type': '5', 'same': '38,42,', 'opposite': '40,44', 'answerA': '38,42,', 'answerB': '40,44'}
No question found for id
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/GIA_practice/game_gia.py", line 395, in <module>
     app.run()
   File "/usr/lib/python3/dist-packages/kivy/app.py", line 955, in run
     runTouchApp()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 383, in idle
     self.dispatch_input()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 302, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/usr/lib/python3/dist-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
   File "/GIA_practice/game_gia.py", line 137, in check_answer_update_score_and_add_new_question
     self.update_layout_with_new_question(func)
   File "/GIA_practice/game_gia.py", line 302, in update_layout_with_new_question
     super().update_layout_with_new_question(func)
   File "/GIA_practice/game_gia.py", line 112, in update_layout_with_new_question
     self.question,self.answer = func()
   File "/GIA_practice/gia_algo.py", line 204, in reasoning
     return [fact, question, list(names.values())], name_answer
 UnboundLocalError: local variable 'question' referenced before assignment